# Generated by Django 5.0.14 on 2025-10-16 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nimi')),
            ],
            options={
                'verbose_name': 'Raaka-aine',
                'verbose_name_plural': 'Raaka-aineet',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nimi')),
                ('description', models.TextField(blank=True, verbose_name='Kuvaus')),
                ('instructions', models.TextField(verbose_name='Valmistusohjeet')),
                ('prep_time', models.PositiveIntegerField(help_text='Minuutteina', verbose_name='Valmistusaika')),
                ('cook_time', models.PositiveIntegerField(help_text='Minuutteina', verbose_name='Kypsennysaika')),
                ('servings', models.PositiveIntegerField(verbose_name='Annokset')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Luotu')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Päivitetty')),
            ],
            options={
                'verbose_name': 'Resepti',
                'verbose_name_plural': 'Reseptit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(help_text="esim. '2 dl', '500 g', '1 kpl'", max_length=50, verbose_name='Määrä')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Raaka-aine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe', verbose_name='Resepti')),
            ],
            options={
                'verbose_name': 'Reseptin raaka-aine',
                'verbose_name_plural': 'Reseptin raaka-aineet',
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
